### ISSUE TITLE
Accessing to raw client

### ISSUE THREAD

**Issue by jibaku** [sebleier/django-redis-cache#104]
Why not adding a function/method to access to the raw redis client ? For example to have access to the more advanced function of redis.

**Comment by sebleier** [comment]
Hi @jibaku, you can already access the raw client.  Use the `get_client` method to access it.  Here's the [code](https://github.com/sebleier/django-redis-cache/blob/master/redis_cache/backends/single.py#L250). I'll add some documentation in the near future to clarify how this works.

**Comment by jibaku** [comment]
I've seen that, but the key arg seems strange, since it's not used in the code.
