### ISSUE TITLE
PICKLE_VERSION doesn't seem to work

### ISSUE THREAD

**Issue by mlissner** [sebleier/django-redis-cache#108]
I have a [strange problem][1] that seems to be related to the version of pickle being used in my cache, and so I'm looking at this area of my code somewhat closely. Today I set up my config as follows:

    CACHES = {
        'default': {
            'BACKEND': 'redis_cache.RedisCache',
            'LOCATION': 'localhost:6379',
            'OPTIONS': {
                'PICKLE_VERSION': 1,
            },
        },
    }

Which should set `PICKLE_VERSION` to 1. However, when I'm debugging my code, I set a breakpoint on like 42 of serializers.py, which is the last line of this class:

    class PickleSerializer(object):
        def __init__(self, pickle_version=-1):
            self.pickle_version = pickle_version
    
        def serialize(self, value):
            return pickle.dumps(value, self.pickle_version)
    
        def deserialize(self, value):
            return pickle.loads(smart_bytes(value))

When I'm on that last line, if I look at `self.pickle_version`, I'm expecting to see it say 1, but instead it says -1, the default. I haven't looked deeply in this codebase (yet, sigh), but this looks very suspicious.

Thanks for the great package.

[1]: https://stackoverflow.com/questions/33356687/typeerror-from-django-cache

**Comment by sebleier** [comment]
Thanks @mlissner for the report!  You are indeed correct this wasn't working as advertised.  I fixed the issue and released [1.6.5](https://pypi.python.org/pypi/django-redis-cache/1.6.5) to PyPI.

Cheers

**Comment by mlissner** [comment]
Wow, that was a fantastically fast fix! Thank you!
