### ISSUE TITLE
redis password error in location

### ISSUE THREAD

**Issue by jason9797** [sebleier/django-redis-cache#109]
find this document http://django-redis-cache.readthedocs.org/en/latest/advanced_configuration.html#password
the password setting is like this

127.0.0.1:6379
/path/to/socket
redis://[:password]@localhost:6379/0
rediss://[:password]@localhost:6379/0
unix://[:password]@/path/to/socket.sock?db=0

but i set redis://[:password]@localhost:6379/0  replace password into my custom redis password.
It also give me ResponseError: invalid password
and I try to print password,It has add the str ']' in my password.
and i change redis://[:mypassword@localhost:6379/0,
everything is ok.
maybe the doc need update or just my misunderstanding.
thanks

**Comment by jason9797** [comment]
sorry, something wrong with celery and django-redis-cache.

**Comment by shanx** [comment]
does this mean this is no longer an issue? please close the ticket in that case. keep thing nice and tidy :)

**Comment by jason9797** [comment]
no,this is really exists in django-celery and django-redis-cache.but finally I give up to use django-redis-cache, because I have no way to solve it. 
I will close this issues.
