### ISSUE TITLE
How to use get_or_set to avoid stampede?

### ISSUE THREAD

**Issue by grantjenks** [sebleier/django-redis-cache#112]
I was looking at the source at https://github.com/sebleier/django-redis-cache/blob/master/redis_cache/backends/base.py#L403 and I wondered what would happen if the dog pile lock were not None? Seems like the returned value would then be None. But I would expect it to the result of my function. Am do you use the get_or_set api to avoid a stampede?

**Comment by sebleier** [comment]
> But I would expect it to the result of my function. Am do you use the get_or_set api to avoid a stampede?

Yeah, that's the idea. If the function passed in is expensive, then you don't want to keep executing the function excessively. So this implementation returns `None` if the function is currently executing in a different thread/process.

**Comment by grantjenks** [comment]
So I have to call the function myself if it returns None? That won't avoid the stampede. Or I have to put the call in a loop to keep retrying?

Have you tested this functionality?
