### ISSUE TITLE
Behavior of incr() doesn't reflect what redis actually does when the key does not exist

### ISSUE THREAD

**Issue by jingsong** [sebleier/django-redis-cache#113]
According to Redis docs for the INCR command:

>Increments the number stored at key by one. If the key does not exist, it is set to 0 before performing the operation.

However, django-redis-cache implements it in such a way that if the key does not exist, a ValueError is raised. 

```python
    def incr(self, client, key, delta=1):
        """Add delta to value in the cache. If the key does not exist, raise a
        `ValueError` exception.
        """
        exists = client.exists(key)
        if not exists:
            raise ValueError("Key '%s' not found" % key)
        try:
            value = client.incr(key, delta)
        except redis.ResponseError:
            key = key._original_key
            value = self.get(key) + delta
            self.set(key, value, timeout=None)
        return value
```

The problem with this approach is the additional operation required to set the key when the key does not exist. When initializing a large set of counters, the additional operation is rather wasteful.

Is there a reason for the implementation to be this way?

**Comment by sebleier** [comment]
> Is there a reason for the implementation to be this way?

I agree it seems rather wasteful, but I was following the functionality as Django's cache backends.[1]

I wouldn't be opposed to adding a keyword argument that instructs the method to follow Redis' behavior, since that would be useful for your cited example of initializing a large set of counters.

[1] https://github.com/django/django/blob/master/django/core/cache/backends/base.py#L177-L187

**Comment by jingsong** [comment]
That makes sense.

I ended up reworking my implementation and settled on Postgres as an ultimately better solution for my particular case. If this issue every sprouts up again, will definitely submit a pull request.

**Comment by sebleier** [comment]
Cheers
