### ISSUE TITLE
Default timeout

### ISSUE THREAD

**Issue by Tecktron** [sebleier/django-redis-cache#114]
I just wanted to know a bit more about the default timeout. Is this set from the timeout in the cache settings (like django default)? Like so:

```
CACHES = {
    'default': {
        'BACKEND': 'redis_cache.RedisCache',
        'TIMEOUT': 300, # timeout in seconds, this would be 5 minutes
...
```
Or from somewhere else?
Thanks.

**Comment by sebleier** [comment]
Yeah, that's precisely how it's specified.  You can also, of course, specify the default when setting values.
