### ISSUE TITLE
How to configure ssl in redis setting?

### ISSUE THREAD

**Issue by NirmalVatsyayan** [sebleier/django-redis-cache#117]
I need to configure django-redis-cache with django using following params.

Hostname  
Port
Password
DB
SSL

Apart from SSL configuration everything, i found other configuration on doc. Kindly let me know how to configure it in django setting.

**Comment by nickromano** [comment]
You'll need to use the connection string `rediss://` instead of `redis://` to get SSL working.

https://github.com/sebleier/django-redis-cache/blob/1b2be04a76891e874f6a1ea8cd3562ed1ecd2a33/redis_cache/utils.py#L68

**Comment by salmicrosoft** [comment]
You may also want to look at the port number - it's common to use `6380` for the SSL port
