### ISSUE TITLE
Facing issue __init__() got an unexpected keyword argument 'connection_class'.

### ISSUE THREAD

**Issue by NirmalVatsyayan** [sebleier/django-redis-cache#118]
I am configuring redis cache in django setting using format given in document for SSL connection.
rediss://[:password]@localhost:6379/0

But i am facing issue ****init**() got an unexpected keyword argument 'connection_class'**

When i see the traceback i find 'connection_class': <class 'redis.connection.SSLConnection'> value in kwargs in redis_cache/backends/base.py in create_client line number 182.

Kindly assist, setting up redis connection is the major thing in my project.

**Comment by jar349** [comment]
This is because `parse_connection_kwargs` in utils.py checks to see if the `url.scheme` is 'rediss' and then adds `url_options['connection_class'] = SSLConnection`.  Instead, it needs to set add `url_options['ssl'] = True`

**Comment by ZoidBB** [comment]
Why was this closed? This bug is still reproducible in master

**Comment by ZoidBB** [comment]
@jar349 unfortunately simply changing the kwargs dictionary to use 'ssl' as the key, breaks the connection pool creation (which doesn't accept the ssl keyword)

**Comment by sfernandezf** [comment]
Hi we are having this issue as well

**Comment by jackdh** [comment]
Still having this issue.

**Comment by jar349** [comment]
You're welcome to fork and use the fix that I described above.  It worked for us.
