### ISSUE TITLE
Handle wildcard deletion of keys

### ISSUE THREAD

**Issue by airstrike** [sebleier/django-redis-cache#38]
Redis allows us to find glob-style wildcard-matching keys with the use of the KEYS command[0]

assuming keys 'apple', 'banana', 'boat':

```
redis 127.0.0.1:6379> keys *
1) "apple"
2) "banana"
3) "boat"
redis 127.0.0.1:6379> keys a*
1) "apple"
```

It would be interesting to be able to do something like

```python
cache.delete_wildcard("a*")
```

and other similar operations.

Cheers!

[0] http://redis.io/commands/keys

**Comment by camilonova** [comment]
@sebleier Can you merge this one?

**Comment by sebleier** [comment]
Merge and available in the latest release.
