### ISSUE TITLE
No way to specify socket_timeout

### ISSUE THREAD

**Issue by stantonk** [sebleier/django-redis-cache#47]
Looks like there is no way to specify the socket_timeout in the OPTIONS, and the default socket_timeout in the underlying redis-py is None. It would be prudent to add the ability to set this so things don't hang if a connection can't be made.

**Comment by jorgecarleitao** [comment]
I believe this is not an issue anymore:

```python

'OPTIONS': {
            'DB': 1,
            'IGNORE_EXCEPTIONS': True,
            'SOCKET_TIMEOUT': 2,
        }
```

**Comment by sebleier** [comment]
I've added a socket timeout and socket create timeout in the latest version.  Docs [here](http://django-redis-cache.readthedocs.org/en/latest/advanced_configuration.html#socket-timeout-and-socket-create-timeout)
