### ISSUE TITLE
make_key does prepends odd values

### ISSUE THREAD

**Issue by dougvk** [sebleier/django-redis-cache#56]
I wanted to retrieve the key 'GOOG' from my redis instance:

```
In [51]: cache.make_key('GOOG')
Out[51]: u':1:GOOG'
```

why does it do this?

**Comment by sebleier** [comment]
Behind the curtains, django uses a key function to add a version number to transform the key.  That way you can invalidate your data by changing the version number when requesting the key from the cache.
