### ISSUE TITLE
'module' object has no attribute 'simple_class_factory'

### ISSUE THREAD

**Issue by yibuyisheng** [sebleier/django-redis-cache#64]
![e42186bb-0013-4c2a-9ca1-9c738e654eb1](https://cloud.githubusercontent.com/assets/2581682/2663456/2b169a60-c05a-11e3-95a0-4c8b5d620425.png)

**Comment by rohan1gupta** [comment]
type redis-cli and then FLUSHALL

**Comment by mlissner** [comment]
> type redis-cli and then FLUSHALL

Good lord, don't do this. This issue is caused by django 1.10 having a different pickle strategy than 1.9. When you upgrade, you get incompatibilities. If you do FLUSHALL, you'll flush your ENTIRE redis DB, not just the issues with Django. Don't do that.

**Comment by beenooyadav** [comment]
Is there any solution other than flushing all
