### ISSUE TITLE
Unable to specify pickle protocol version

### ISSUE THREAD

**Issue by nathan-osman** [sebleier/django-redis-cache#65]
I have just finished porting our Django codebase to Python 3. Our plan is to run both Python 2 and Python 3 interpreters in separate virtualenvs on the same webserver and load balance traffice between the two of them for testing purposes.

Unfortunately, it seems they can't both use the same Redis cache. The default pickle protocol for Python 3 is version 3. This version is incompatible with all versions of Python 2. Therefore, anything created by Django while running under the Python 3 interpreter will cause an error when retrieved under Python 2.

It would be awesome if there was an extra parameter to get/set or even a configuration setting that provided a means of manually overriding the protocol version used.

**Comment by sebleier** [comment]
Latest release supports specifying the pickle protocol number.

**Comment by mvdwaeter** [comment]
that relevant part of the doc has now moved to here:
http://niwinz.github.io/django-redis/latest/#_pickle_version
Update your settings like so:



    CACHES = {
        "default": {
            # ...
            "OPTIONS": {
                "PICKLE_VERSION": -1  # Use the latest protocol version (default), for py2 compatibility use 2
            }
        }
    }

**Comment by sebleier** [comment]
You can also view the relevant part of the docs for this package here:
http://django-redis-cache.readthedocs.org/en/latest/advanced_configuration.html#pickle-version
```python 
CACHES = {
    'default': {
        'OPTIONS': {
            'PICKLE_VERSION': 2,
            ...
        },
        ...
    },
}
```
