### ISSUE TITLE
RemovedInDjango19Warning

### ISSUE THREAD

**Issue by epicserve** [sebleier/django-redis-cache#68]
I'm getting the following warning:

```
/Users/xxxx/.virtualenvs/xxxxx/lib/python2.7/site-packages/redis_cache/cache.py:3: RemovedInDjango19Warning: django.utils.importlib will be removed in Django 1.9.
  from django.utils import importlib
```

**Comment by epicserve** [comment]
I guess I should note I'm using the current pypi version 0.13.0.

**Comment by sebleier** [comment]
Django is deprecating its version of `importlib` in favor of the standard lib's version.  I've made the updates to make the library compatible with Django 1.9.  558c2a4

**Comment by epicserve** [comment]
@sebleier Cool, thanks! Will this be made into a release soonish?

**Comment by sebleier** [comment]
Sorry, forgot to mention it's already on pypi as 0.13.1
