### ISSUE TITLE
support for read vs write replicas

### ISSUE THREAD

**Issue by snarfed** [sebleier/django-redis-cache#69]
first off, thanks for django-redis-cache, we love it!

we have a feature request: we'd love to use a redis replication group with both read only and read/write replicas. any chance you could support that in the future? i'm guessing we'd either provide multiple django cache backends with well-known names, or we'd specify the read vs write endpoints in `OPTIONS`, and you'd pick the right one for each cache operation. or however you want!

(related to #3 and #31, but not the same.)

thanks in advance!

**Comment by sebleier** [comment]
Hi @snarfed, I have that feature in an unstable [1.0](https://github.com/sebleier/django-redis-cache/tree/unstable) branch.  Once I merge it into master, I'll let you know and close this issue.

**Comment by snarfed** [comment]
woo that's great news! thanks!

**Comment by sebleier** [comment]
This is available on the latest release.  More docs coming soon, but the [tests](https://github.com/sebleier/django-redis-cache/blob/master/tests/testapp/tests/master_slave_tests.py#L14-L34) should give you a clue on usage.  Cheers

**Comment by snarfed** [comment]
yay, thank you @sebleier! can't wait to try it!

**Comment by sebleier** [comment]
If you run into any problems, let me know!
