### ISSUE TITLE
Issue With Expires Header - Possible config problem ?

### ISSUE THREAD

**Issue by muhammedabad** [sebleier/django-redis-cache#70]
Hi,

I seem to be having an issue with my expires / last modified header values not updating after they are set initially.

```http
HTTP/1.1 200 OK
Cache-Control: max-age=120
Content-Type: text/html; charset=utf-8
Date: Sat, 18 Apr 2015 09:52:44 GMT
Expires: Sat, 18 Apr 2015 07:31:30 GMT
Last-Modified: Sat, 18 Apr 2015 07:29:30 GMT
Server: nginx/1.2.1
Vary: Cookie
Connection: keep-alive
```
Note that the time of the request is well after the expires value, but it does not update and still serves up the old version of the page.

My settings configs are as follows:

```python
CACHES = {
'default': {
    'BACKEND': 'redis_cache.RedisCache',
    'LOCATION': 'my-redis-server:6379',
    },
}

MIDDLEWARE_CLASSES = (
    'django.middleware.cache.UpdateCacheMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.middleware.cache.FetchFromCacheMiddleware'
)
```
And I've added the @cache_page decorator to my view:

```python
@cache_page(120)
def home(request):
    ...
```
Can anyone tell me what the issue is ?

**Comment by sebleier** [comment]
If you switch to the `django.core.cache.backends.locmem.LocMemCache` backend, do you see the same problem?  If you don't, you might want to check the ttl of the key.  If it's greater than 120 or is None, there is probably a problem.  If you could provide the version of django-redis-cache, that would help me to track down the problem...if it still exists.

**Comment by muhammedabad** [comment]
Seems there was a bug in my redis.conf file - re-installing and configuring options again seemed to have solved the issue.

**Comment by sebleier** [comment]
Great, glad you figured out the problem!
