### ISSUE TITLE
django.core.exceptions.ImproperlyConfigured: "server" must be an iterable or string

### ISSUE THREAD

**Issue by mikeedwards** [sebleier/django-redis-cache#80]
When I pass a value of "server" that is type `unicode` instead of `str` I get: 

```
  File "/Users/Mike_Edwards/.virtualenvs/emojicatch/lib/python2.7/site-packages/redis_cache/backends/base.py", line 84, in get_servers
    '"server" must be an iterable or string'
django.core.exceptions.ImproperlyConfigured: "server" must be an iterable or string
```

More specifically, the `django-environ` app is what's passing the value in as `unicode` but it seems like that should work either way.

It looks as though a recent change to get_servers uses `isinstance` narrowly and only allows values that are type `str`:
https://github.com/sebleier/django-redis-cache/commit/f88925a17d5ac7316945b908e8be0e4e6158600c#diff-8fc3ae3ff1cb89b2f4ba473a41661d77R78

I'm using:
python 2.7.6
Django 1.8.2
django-environ 0.3.0

**Comment by sebleier** [comment]
@mikeedwards – The latest release should have fixed that issue, let me know if it works for you.

**Comment by emilioramirez** [comment]
@sebleier yes, I update to django-redis-cache==1.2.1 and works fine. Thanks.

**Comment by sebleier** [comment]
@emilioramirez – Great! Thanks for testing.

**Comment by monokrome** [comment]
Seems like this issue may be back in 2.1.0?

**Comment by wowkin2** [comment]
Same for me 2.1.1.

**Comment by wowkin2** [comment]
Found that in following configuration `REDIS_URL` is empty or not configured. So, works fine.
```python
CACHES = {
    "default": {
         "BACKEND": "redis_cache.RedisCache",
         "LOCATION": os.environ.get('REDIS_URL'),
    }
}
```
FYI, @monokrome
