### ISSUE TITLE
Release version with py3 fixes

### ISSUE THREAD

**Issue by imankulov** [sebleier/django-redis-cache#82]
Hello @sebleier 

Can you please make a new release with Python3 fixes you made recently. I would love to use the version from PyPI, but it's current version 1.1.0 is broken in Python 3. Thank you!

**Comment by sebleier** [comment]
[1.1.1](https://pypi.python.org/pypi/django-redis-cache/1.1.1) is up on PyPI, let me know if there are any problems.

**Comment by imankulov** [comment]
Thanks a lot, @sebleier, I will :+1:
