### ISSUE TITLE
Error Python3.2 django 1.8.2

### ISSUE THREAD

**Issue by PabloCariel** [sebleier/django-redis-cache#83]
Django Version:	1.8.2
Exception Type:	ImproperlyConfigured
Exception Value:	
Port value must be an integer
Exception Location:	/usr/local/lib/python3.2/dist-packages/redis_cache/backends/base.py in create_client, line 164
Python Executable:	/usr/bin/python3.2

Install Release 1.1.1

**Comment by sebleier** [comment]
I believe I've fixed this issue with the [latest release](https://github.com/sebleier/django-redis-cache/tree/1.2.1) ([PyPI](https://pypi.python.org/pypi/django-redis-cache/1.2.1))

Tests pass for Python 3.2 https://travis-ci.org/sebleier/django-redis-cache
