### ISSUE TITLE
Documentation: default values for configuration options

### ISSUE THREAD

**Issue by devoto13** [sebleier/django-redis-cache#92]
In the [documentation](http://django-redis-cache.readthedocs.org/en/latest/advanced_configuration.html) configuration options are described, but one thing is missing: default values for each option, which are used, when option is not set.

For example it's not clear, whether any connection pool is used by default and which one? I can open sources and investigate this, but it's much more convenient to have this described in the documentation.

**Comment by sebleier** [comment]
Thanks for the feedback, I'll update the docs tonight.

**Comment by devoto13** [comment]
Thank you!

**Comment by sebleier** [comment]
The docs are still a work in progress, so if you see anything wrong, incomplete, or needs rewording, just let me know.  I appreciate it!

**Comment by devoto13** [comment]
Sure. Besides default values it is clear for me.

One more minor thing, which would be nice to have are "Next" and "Previous" buttons to go to the next and previous pages in the documentation (instead of using back button in browser and clicking on the next topic in menu).

Thank you for a great package BTW :+1:

**Comment by sebleier** [comment]
I haven't added the Next and Previous buttons yet, but I've added default information for different configuration options.
