### ISSUE TITLE
get_or_set not using timeout

### ISSUE THREAD

**Issue by chripede** [sebleier/django-redis-cache#96]
When using get_or_set with a timeout specified, the timeout is not respected and simply set as None/-1
The lock key is also set to -1. Don't know if that's intended.

https://github.com/sebleier/django-redis-cache/blob/master/redis_cache/backends/base.py#L400
None is sent to the _set method.

To me it also seems like the lock key is set twice? First with a timeout of None and then later with the actual timeout, but since it's already set it's ignore.

**Comment by sebleier** [comment]
@chripede – I cleaned up the implementation a little bit and made sure the timeout was being applied to the key.  Let me know if it works for you.

**Comment by chripede** [comment]
Works perfectly :ok_hand:
